server:
  port: ${GATEWAY_PORT:9000}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: example-service
          uri: lb://example-service
          predicates:
            - Path=/api/example/**

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_USER:user}:${DISCOVERY_PASSWORD:qwerty}@${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:9000}/eureka/

